apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mood-analyzer
  description: Mood analyzer
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=mood-analyzer'
spec:
  type: service
  lifecycle: integration
  owner: hope-dev-team2
  system: devx-mood
  subcomponentOf: mood-sensors
  dependsOn: 
    - resource:brownfield
    - resource:reading
  consumesApis:
    - datacheck-apis
    - sentiment-apis