apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mood-analyzer
  description: Mood analyzer
spec:
  type: service
  lifecycle: integration
  owner: dekt-dev-team2
  system: devx-mood
  dependsOn: 
    - resource:brownfield
    - resource:reading
  consumesApis:
    - datacheck-apis
    - sentiment-apis
    - mood-sensors-apis